version: '2.2'

services:
  postgresql:
    image: postgres:11.3
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_USER: street-art
      POSTGRES_PASSWORD: street-art
      POSTGRES_DB: street-art-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isalready -d street-art-db -U street-art"]
      interval: 15s
      timeout: 10s
      retries: 10
