spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/street-art-db
    username: street-art
    password: street-art
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        hibernate:
          ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
    show-sql: true
  flyway:
    locations: classpath:db/migration/postgresql
